apiVersion : apps/v1
kind: Deployment
metadata:
  name: "playground2-fa73"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "playground2-fa73"
  template:
    metadata:
      labels:
        app: "playground2-fa73"
    spec:
      containers:
        - name: "playground2-fa73"
          image: "seanmckdemo.azurecr.io/playground2"
          ports:
          - containerPort: 80